[build-system]
requires = ["setuptools>=58.0.4", "wheel"]
build-backend = "setuptools.build_meta"

[build-system.backends.go]
name = "go"
requires = ["go>=1.16"]

[build-system.backends.npm]
name = "npm"
requires = ["npm>10.4.0"]
