[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
name = "myenv"
channels = [
    "conda-forge"
]
dependencies = [
    "jax",
    "jupyter",
    "ipykernel",
    "openai",
    "numpy",
    "pandas",
    "typing",
    "pydantic",
    "httpx"
]