[tool.mypy]
mypy_path = ["cognosis/cognosis/db"]
],

testing = [
    "pytest==7.4.2",
    "pytest-asyncio==0.21.1",
]

dev = ["cognosis[lint,static-analysis,testing]"]

[tool.pytest.ini_options]
filterwarnings =["ignore::DeprecationWarning"]

[tool.mypy]
strict = true
python_version = "3.9"
ignore_missing_imports = false
install_types = false
non_interactive = false

# from https://blog.wolt.com/engineering/2021/09/30/professional-grade-mypy-configuration/
disallow_untyped_defs = false
no_implicit_optional = false
check_untyped_defs = false
warn_return_any = false
show_error_codes = false
warn_unused_ignores = false

disallow_incomplete_defs = false
disallow_untyped_decorators = false
disallow_any_unimported = true

[tool.black]
line-length = 88
target-version = ['py38']
[tool.ruff]
fix = true
line-length = 88
target-version = "py38"
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "Q",  # flake8-quotes
]
ignore = [
    "E501",  # line too long, handled by black
    "C901",  # too complex
]

[tool.ruff.pydocstyle]
mypy_path = "cognosis/cognosis/db"
convention = "google"
include = '\.pyi?$'

[tool.ruff]
fix = true
line-length = 88
target-version = "py38"
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "Q",  # flake8-quotes
]
ignore = [
    "E501",  # line too long, handled by black
    "C901",  # too complex
]

[tool.ruff.pydocstyle]
mypy_path = "cognosis/cognosis/db"
convention = "google"

[tool.bandit]
